FROM mcr.microsoft.com/dotnet/core/sdk:2.2.401-bionic
WORKDIR /app
COPY . ./

ARG PGUSER
ARG PGPASS
ARG PGHOST
ARG PGDATABASE

ENV PGUSER=${PGUSER}
ENV PGPASS=${PGPASS}
ENV PGHOST=${PGHOST}
ENV PGDATABASE=${PGDATABASE}

RUN dotnet restore
RUN ["wget", "-q", "https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/6.0.1/flyway-commandline-6.0.1-linux-x64.tar.gz"]
RUN ["tar", "-xvf", "flyway-commandline-6.0.1-linux-x64.tar.gz"]
RUN ["chmod", "+x", "./Scripts/migrate.sh"]
