version: '3.7'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev
    ports:
      - "5432:5432"
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    container_name: property-api
    image: property-api
    build:
      context: ./PropertyApi
    ports:
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - ~/.aws/:/root/.aws:ro
      - ./PropertyApi:/app
    command: dotnet watch run --urls=http://+:5000
